dist: trusty
sudo: required

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - gcc-5
      - g++-5
      - cmake
      - cmake-data

before_install:
  - make -v
  - cmake --version
#  - git clone https://github.com/Kitware/CMake.git
#  - cd CMake
#  - git checkout v3.8.1
#  - ./bootstrap && make && sudo make install
#  - cd ..
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - git checkout release-1.8.0
  - mkdir build && cd build
  - cmake .. && make && sudo make install
  - cd ../..

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./unit_tests
  - ./system_tests
