dist: trusty

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

before_install:
  - make -v
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./unit_tests
  - ./system_tests
