dist: trusty
sudo: required

language: cpp

before_install:
  - sudo apt-get install make cmake
  - make -v
  - cmake --version

scripts:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./unit_tests
  - ./system_tests
